version: '3.10'

services:
  social_back:
    build: ./
    command: python3 manage.py runserver localhost:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.test.env
    depends_on:
      - social_db
  social_db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - social_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5431:5432
    env_file:
      - ./.test.env
    # environment:
    #   - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  social_postgres_data:
